# Dockerfile.ingester

FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Run with unbuffered logs so Docker shows logs instantly
CMD ["python", "-u", "ingester.py"]
